version: '3'

services:

  ceiamin_backend:
    container_name: c_rfb_ceiamin_backend
    hostname: ceiamin_backend
    #image: jesjf/jjprivate:playip_app_aiohttp
    image: rfb_ceiamin_backend
    ports:
      - "8001:80"
    restart: unless-stopped  # o serviço fica no ar, mesmo que a máquina host seja reiniciada. só para por comando explícito

  ceiamin_frontend:
    container_name: c_rfb_ceiamin_frontend
    hostname: ceiamin_frontend
    #image: jesjf/jjprivate:playip_app_aiohttp
    image: rfb_ceiamin_frontend
    ports:
      - "8000:80"
    restart: unless-stopped  # o serviço fica no ar, mesmo que a máquina host seja reiniciada. só para por comando explícito


  nginx:
    restart: unless-stopped
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      # o arquivo que no host é ./reverse_proxy.conf, dentro do container é /etc/nginx/conf.d/default.conf
      # Note que não é uma cópia, mas um mapenamento dinâmico
      #O nginx está dentro do container e procura por /etc/nginx/conf.d/default.conf
      - ./www:/etc/www
      #Agora o mapeamento foi de um diretório

